---
title: "Population Statistics Data Extraction"
author: "Francine Stephens"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE,
                      echo = FALSE)

library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
options(tigris_use_cache = TRUE)

# Parameters
data_folder <- "data/"
source("geographic_parameters.R")

```



# Data Import
```{r}
# Population
pop_estimates <- get_estimates(geography = "county",
                               year = 2022,
                               geometry = TRUE,
                               resolution = "20m"
                               )


# Places
places_sf <- places(state = "48", year =2022)

county_seats <- places_sf %>% 
  filter(NAME %in% county_table$county_seats) %>% 
  mutate(geometry = st_centroid(geometry)) 

```


## Export Data
```{r}
write_rds(pop_estimates, paste0(data_folder,
                                "population_estimates_2022.rds"))

write_rds(county_seats, paste0(data_folder, 
                               "county_seats_sf.rds"))
```

