---
title: "Maps of Texas Mega-regions"
author: "Francine Stephens"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tigris)
library(tidycensus)
library(tmap)
library(sf)
library(od)
library(extrafont)
loadfonts(device = "win")
options(tigris_use_cache = TRUE)

# Parameters
data_folder <- "data/"
outputs_folder <- "outputs/"
source("geographic_parameters.R")
us_prj <- 5070
Sys.setenv(CENSUS_KEY="99ccb52a629609683f17f804ca875115e3f0804c")

# Data
county_seats_sf <- readRDS(paste0(
  data_folder, 
  "county_seats_sf.rds"))
pop_estimates <- readRDS(paste0(
  data_folder, 
  "population_estimates_2022.rds"))
#cw <- readxl::read_excel("cbsa_met_county_fips_cw.xlsx")
dfw_flows <- readRDS(paste0(data_folder, "dfw_movedin.rds"))
saa_flows <- readRDS(paste0(data_folder, "saa_movedin.rds"))

us_states <- states(cb = TRUE, year =2022) %>% 
  shift_geometry()

metros <- core_based_statistical_areas(cb = TRUE, year = 2021) %>% 
  shift_geometry() %>% 
  st_transform(., crs = us_prj) %>% 
  st_centroid()

metro_flows <- get_flows(
  geography = "metropolitan statistical area",
  year = 2020,
  geometry = TRUE
  )  %>% 
  shift_geometry()
```

# Clean Data
```{r}
pop_estimates_aoi <- pop_estimates %>% 
  mutate(state = substr(GEOID, 1, 2),
         county_name =  str_remove_all(NAME , " County, Texas")) %>% 
  filter(state == "48" & county_name %in% county_table$all_counties) %>% 
  pivot_wider(names_from = "variable",
              values_from = "value") %>% 
  mutate(birth_death_ratio = BIRTHS/DEATHS,
         domestic_int_ratio = DOMESTICMIG/INTERNATIONALMIG) %>% 
  left_join(., county_table, by = c("county_name" = "all_counties"))

```

# Reference Map of counties in Metro Regions
```{r}
## Font to Select
# Rockwell already registered with windowsFonts().
# Rockwell Condensed already registered with windowsFonts().
# Rockwell Extra Bold

# Color definition
canva_orange <- "#f49619"
c_white <- "#ffffff"
web_orange <- "#e6a532"
web_blue <- "#3273e6"

# SA-A
saa_county_layer <- pop_estimates_aoi %>%  
          mutate(COUNTY_NAME = toupper(county_name)) %>%
         filter(megaregion == "San Antonio-Austin") %>% 
         st_transform(., crs = 6587)

saa_county_seats <- county_seats_sf %>% 
  filter(NAME %in% saa_county_layer$county_seats) %>% 
  mutate(COUNTY_SEAT = toupper(NAME)) %>% 
         st_transform(., crs = 6587)
  
  
ggplot() + 
  geom_sf(data = saa_county_layer, 
          fill = canva_orange, color = c_white, 
          size = 2, linewidth = 2) + 
  geom_sf(data = saa_county_seats, shape="\u2605", 
          size=8, color = c_white) +
  geom_sf_text(data = saa_county_seats, 
            aes(label=COUNTY_SEAT, hjust = 1, vjust= -1), 
            size=2.5, color = c_white
            ) + 
  coord_sf(datum = NA) + 
  theme_void(base_family = "Rockwell Extra Bold", base_size = 12)

ggsave(paste0(outputs_folder, 
              "saa.png"))
```

```{r}
# DFW
dfw_county_layer <- pop_estimates_aoi %>%  
          mutate(COUNTY_NAME = toupper(county_name)) %>%
         filter(megaregion == "Dallas-Fort Worth") %>% 
         st_transform(., crs = 2276)

dfw_county_seats <- county_seats_sf %>% 
  filter(NAME %in% dfw_county_layer$county_seats) %>% 
  mutate(COUNTY_SEAT = toupper(NAME)) %>% 
         st_transform(., crs = 2276)


ggplot(
 ) + 
  geom_sf(data = dfw_county_layer, 
          fill = canva_orange, color = c_white, 
          size = 2, linewidth = 2) + 
    geom_sf(data = dfw_county_seats, shape="\u2605", 
          size=8, color = c_white) +
  geom_sf_text(data = dfw_county_seats, 
            aes(label=COUNTY_SEAT, hjust = 0.5, vjust= -1), 
            size=2.5, color = c_white
            ) + 
  coord_sf(datum = NA) + 
  theme_void(base_family = "Rockwell Extra Bold",
             base_size = 12)
ggsave(paste0(outputs_folder, 
              "dfw.pdf"))
```

## Map of Flows
```{r}

# US STATES LAYER
dropped_geoms <- c("66", "60", "69", "78")
us_states_layer <- us_states %>% 
            filter(!GEOID %in% dropped_geoms) %>% 
  st_transform(., crs = 5070)



# METRO LAYERS
metros_flows_coords <- metros %>% 
  select(GEOID, NAME, NAMELSAD) %>%
  mutate(origin_long = unlist(map(.$geometry,1)),
           origin_lat = unlist(map(.$geometry,2))) %>% 
  st_set_geometry(NULL) 

## Centroids
saa_cent <- saa_county_layer %>% 
          st_transform(., crs = us_prj) %>% 
  group_by(megaregion) %>% 
  summarize() %>% 
  ungroup() %>%
  st_centroid() %>% 
  mutate(dest_long = unlist(map(.$geometry,1)),
         dest_lat = unlist(map(.$geometry,2))) %>% 
  st_set_geometry(NULL)

dfw_cent <- dfw_county_layer %>% 
          st_transform(., crs = us_prj) %>% 
  group_by(megaregion) %>% 
  summarize() %>% 
  ungroup() %>%
  st_centroid() %>% 
  mutate(dest_long = unlist(map(.$geometry,1)),
         dest_lat = unlist(map(.$geometry,2))) %>% 
  st_set_geometry(NULL)

## FLOWS

saa_flows_od <- saa_flows %>% 
  rename(d_megaregion = "megaregion",
         o_metro = "Metro",
         o_metro_id = `CBSA Code`
         ) %>% 
  # Dest cent
  cbind(., saa_cent %>% 
          select(dest_long, dest_lat)) %>% 
  # Origin Cent
  left_join(., metros_flows_coords %>% 
              select(GEOID, NAMELSAD, origin_long, origin_lat),
            by = c("o_metro_id" = "GEOID"))%>% 
  filter(!is.na(origin_lat)) %>% 
  select(o_metro_id, dest_long, dest_lat, origin_long, origin_lat, percent, movedin, NAMELSAD) %>% 
  slice(1:100) %>%
  mutate(`Destination Metro` = "San Antonio-Austin")
  

dfw_flows_od <- dfw_flows %>% 
  rename(d_megaregion = "megaregion",
         o_metro = "Metro",
         o_metro_id = `CBSA Code`
         ) %>% 
  # Dest cent
  cbind(., dfw_cent %>% 
          select(dest_long, dest_lat)) %>% 
  # Origin Cent
  left_join(., metros_flows_coords %>% 
              select(GEOID, NAMELSAD, origin_long, origin_lat),
            by = c("o_metro_id" = "GEOID"))%>% 
  filter(!is.na(origin_lat)) %>% 
  select(o_metro_id, dest_long, dest_lat, origin_long, origin_lat, percent, movedin, NAMELSAD)  %>% 
  slice(1:100) %>%
  mutate(`Destination Metro` = "Dallas-Fort Worth")


all_flows <- rbind(saa_flows_od,
      dfw_flows_od) %>% 
  mutate(od_id = paste0(NAMELSAD, " to ", `Destination Metro`),
         percent = ifelse(NAMELSAD == "San Francisco-Oakland-Berkeley, CA Metro Area" & `Destination Metro` == "San Antonio-Austin", 3.64, percent), 
         percent = ifelse(NAMELSAD == "San Francisco-Oakland-Berkeley, CA Metro Area" & `Destination Metro` == "Dallas-Fort Worth", 2.60, percent),
        percent = ifelse(NAMELSAD == "San Antonio-New Braunfels, TX Metro Area" & `Destination Metro` == "Dallas-Fort Worth", 7.6, percent)
         ) %>% 
  filter(NAMELSAD != "San Jose-Sunnyvale-Santa Clara, CA Metro Area",
         NAMELSAD != "San Antonio-New Braunfels, TX Metro Area")

##
library(sfheaders)

sf <- data.table::as.data.table(all_flows)[
    , {
        geometry <- sf::st_linestring(x = matrix(c(origin_long, dest_long,
                                                   origin_lat, dest_lat), nrow = 2, ncol = 2))
        geometry <- sf::st_sfc(geometry)
        geometry <- sf::st_sf(geometry = geometry)
    }
    , by = od_id
]


sf_flows <- sf %>% 
  st_as_sf(., crs = us_prj) %>%
  separate(od_id, c("Origin", "Destination"), sep = " to ") %>% 
  shift_geometry() %>% 
  st_transform(., crs = us_prj)

write_csv(sf_flows, "flows.csv")
```

```{r}
## MAP
ggplot() + 
  # Base Layer
  geom_sf(data = us_states_layer,
          fill = "#ECECEC", color = "#D3D3D3", size = 2, linewidth = 1.2, alpha = 0.95) + 
  # FLOWS
   geom_curve(data=all_flows, 
              aes(x = origin_long, y = origin_lat,
                                  xend = dest_long, yend = dest_lat,
                                  #linewidth = percent, 
                                  color = `Destination Metro`, alpha = percent),
               arrow = arrow(length = unit(0.05, "cm"), ends = "last", type = "closed"),
              position = position_dodge2(width = 0.3),
              curvature = .2, lineend = "round", size =1) + # all_flows
    # geom_sf(data=sf_flows, aes(linewidth = percent, 
    #                               color = Destination),
    #            arrow = arrow(length = unit(0.03, "cm")), 
    #                          alpha = 0.5, curvature = .2, lineend = "round") +
    #SAA
  #geom_point(data = saa_cent, aes(x = dest_long, y = dest_lat), 
  #            shape="\u2605", size = 4) + 
  # geom_sf(data = saa_county_layer %>%
  #         st_transform(., crs = us_prj),
  #         fill = web_orange, color = web_orange, alpha = 0.2,
  #         size = 2) +
  # DFW
  #geom_point(data = dfw_cent, aes(x = dest_long, y = dest_lat), 
  #           shape ="\u2605",  size = 4) + 
  # geom_sf(data = dfw_county_layer %>%
  #         st_transform(., crs = us_prj),
  #         fill = web_blue, color = web_blue, alpha = 0.2,
  #         size = 2) +
  # Styling
  #scale_linewidth_continuous(range = c(0.5, 4)) + 
  scale_alpha_continuous(range = c(0.2, 1)) + 
  scale_color_manual(values = c(web_blue, web_orange)) + 
  guides(color=guide_legend(title="Destination Metro"),
         alpha = guide_legend(title="New Resident Share (%)")) + 
  coord_sf(datum = NA) + 
  theme_void() + 
  theme(legend.key.size = unit(1.5,"line"),
        legend.position = "bottom")
ggsave("flow_map_draft2.pdf", width = 10)

```

